services:
  alegra-app:
    build: .
    container_name: alegra-app
    ports:
      - '4200:4200'
    volumes:
      - ./:/alegra-app
    environment:
      - STYLE=css
    networks:
      - backend_network
      - internal_network

networks:
  backend_network:
    external: true
  internal_network:
    driver: bridge