version: '3.8'

services:
  db_kitchen:
    build:
      context: .
    environment:
      - POSTGRES_USER=${DB_USER_KITCHEN}
      - POSTGRES_PASSWORD=${DB_PASSWORD_KITCHEN}
      - POSTGRES_DB=${DB_KITCHEN_NAME}
    ports:
      - "${DB_PORT_KITCHEN}:5432"
    networks:
      - backend_network

networks:
  backend_network:
    external: true
