version: '3.8'

services:
  db_order:
    build:
      context: .
    environment:
      - POSTGRES_USER=${DB_USER_ORDER}
      - POSTGRES_PASSWORD=${DB_PASSWORD_ORDER}
      - POSTGRES_DB=${DB_ORDER_NAME}
    ports:
      - "${DB_PORT_ORDER}:5432"
    networks:
      - backend_network

networks:
  backend_network:
    external: true
